cmake_minimum_required(VERSION 4.3.1)
project(korra.example)

find_package(ftxui REQUIRED)
#add_executable(main main.cpp)
#target_link_libraries(main
#  PRIVATE ftxui::screen
#  PRIVATE ftxui::dom
#  PRIVATE ftxui::component
#)

#chat_over_rtmp
#add_executable(chat_over_rtmp chat_over_rtmp/chat_over_rtmp.cpp)
#target_link_libraries(chat_over_rtmp 
#    spdlog
#    PRIVATE ftxui::screen
#    PRIVATE ftxui::dom
#    PRIVATE ftxui::component
#)