enum config_error : int {
    PARSE_VIDEO_WIDTH_INVALID = 0x1000000,
    PARSE_VIDEO_HEIGHT_INVALID,
    PARSE_VIDEO_FPS_INVALID,
    SERIALIZE_VIDEO_WIDTH_INVALID,
    SERIALIZE_VIDEO_HEIGHT_INVALID,
    SERIALIZE_VIDEO_FPS_INVALID,
    PARSE_PIPES_IN_UNDEFINED,
    PARSE_PIPES_OUT_UNDEFINED,
    PARSE_PIPES_IN_TYPE_NOT_STRING,
    PARSE_PIPES_OUT_TYPE_NOT_STRING
};